// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIT-tox1p6cKVBQGW6tSaA67K4BJg2aio',
    appId: '1:82333462214:web:40d008d01cd84690e3b1c7',
    messagingSenderId: '82333462214',
    projectId: 'authpractice-61ae0',
    authDomain: 'authpractice-61ae0.firebaseapp.com',
    databaseURL: 'https://authpractice-61ae0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'authpractice-61ae0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-i4qU46iFocctpcPswRNeQwHU1OKOImo',
    appId: '1:82333462214:android:695fad771ec49199e3b1c7',
    messagingSenderId: '82333462214',
    projectId: 'authpractice-61ae0',
    databaseURL: 'https://authpractice-61ae0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'authpractice-61ae0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXtLOrfyyWhli-57eswUBf9A0CeB03Gb4',
    appId: '1:82333462214:ios:b8f20d0e28d71994e3b1c7',
    messagingSenderId: '82333462214',
    projectId: 'authpractice-61ae0',
    databaseURL: 'https://authpractice-61ae0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'authpractice-61ae0.appspot.com',
    iosClientId: '82333462214-09re1pq8d03jdbcti4ms8jkqcensrrvc.apps.googleusercontent.com',
    iosBundleId: 'com.example.authPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXtLOrfyyWhli-57eswUBf9A0CeB03Gb4',
    appId: '1:82333462214:ios:b8f20d0e28d71994e3b1c7',
    messagingSenderId: '82333462214',
    projectId: 'authpractice-61ae0',
    databaseURL: 'https://authpractice-61ae0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'authpractice-61ae0.appspot.com',
    iosClientId: '82333462214-09re1pq8d03jdbcti4ms8jkqcensrrvc.apps.googleusercontent.com',
    iosBundleId: 'com.example.authPractice',
  );
}
